name: gizmos_hud_example
description: >-
  An example Flutter project to showcase the `gizmos_hud` package.

# Contact Info
homepage: https://gizmos.dev/
repository: https://github.com/GizmosDev/gizmos_hud
issue_tracker: https://github.com/GizmosDev/gizmos_hud/issues

version: 0.1.0-nullsafety.1

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Stricter than Effective Dart
  pedantic: ^1.11.0

  # Load our local `gizmos_hud` package.
  gizmos_hud:
    path: ../

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/confetti.gif
