name: example
description: An example Flutter project to showcase the gizmos_hud package.
version: 0.0.1-alpha.1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter

  # Stricter than Effective Dart
  pedantic: ^1.11.0

  gizmos_hud:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/confetti.gif
