---
name: gizmos_hud_example
description: >-
  An example Flutter project to showcase the `gizmos_hud` package.

# Contact Info
homepage: https://gizmos.dev/
repository: https://github.com/GizmosDev/gizmos_hud
issue_tracker: https://github.com/GizmosDev/gizmos_hud/issues

version: 0.1.0-nullsafety.1

publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  # Load our local `gizmos_hud` package.
  gizmos_hud:
    path: ../

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/confetti.gif
