name: gizmos_hud
description: >-
  A Flutter package for displaying custom HUD's, Toasts, or other screen overlays.

# Contact Info
homepage: https://gizmos.dev/
repository: https://github.com/GizmosDev/gizmos_hud
issue_tracker: https://github.com/GizmosDev/gizmos_hud/issues

version: 0.1.0-nullsafety.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Stricter than Effective Dart
  pedantic: ^1.11.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
